export const actionTypes = {
  GET_PROJECT_LIST_REQUESTED: 'GET_PROJECT_LIST_REQUESTED',
  GET_PROJECT_LIST_SUCCEEDED: 'GET_PROJECT_LIST_SUCCEEDED',
  GET_PROJECT_LIST_FAILED: 'GET_PROJECT_LIST_FAILED',

  GET_PROJECT_REQUESTED: 'GET_PROJECT_REQUESTED',
  GET_PROJECT_SUCCEEDED: 'GET_PROJECT_SUCCEEDED',
  GET_PROJECT_FAILED: 'GET_PROJECT_FAILED',

  PROJECT_SELECTED: 'PROJECT_SELECTED',

  SET_CATEGORY_FILTER: 'SET_CATEGORY_FILTER',
  SET_ADVISOR_FILTER: 'SET_ADIVSOR_FILTER',

  SEARCH_PROJECT_REQUESTED: 'SEARCH_PROJECT_REQUESTED',
  SEARCH_PROJECT_SUCCEEDED: 'SEARCH_PROJECT_SUCCEEDED',
  SEARCH_PROJECT_FAILED: 'SEARCH_PROJECT_FAILED',

  RESET_SEARCH: 'RESET_SEARCH',
}
