export const actionTypes = {
  GET_PROJECT_LIST_REQUESTED: 'GET_PROJECT_LIST_REQUESTED',
  GET_PROJECT_LIST_SUCCEEDED: 'GET_PROJECT_LIST_SUCCEEDED',
  GET_PROJECT_LIST_FAILED: 'GET_PROJECT_LIST_FAILED',

  GET_PROJECT_REQUESTED: 'GET_PROJECT_REQUESTED',
  GET_PROJECT_SUCCEEDED: 'GET_PROJECT_SUCCEEDED',
  GET_PROJECT_FAILED: 'GET_PROJECT_FAILED',

  PROJECT_SELECTED: 'PROJECT_SELECTED',

  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
}
