export const categories = {
  'algorithms': 'Algorithms',
  'art': 'Art',
  'behavior': 'Behavior',
  'data-viz': 'Data Viz',
  'education': 'Education',
  'foodbio-systems': 'Food/Bio Systems',
  'games': 'Games',
  'health': 'Health',
  'installation': 'Installation',
  'internet-of-things': 'Internet of Things',
  'machine-learning': 'Machine Learning',
  'mobile-apps': 'Mobile Apps',
  'musicsound': 'Music/Sound',
  'networking': 'Networking',
  'performance': 'Performance',
  'politics': 'Politics',
  'privacy': 'Privacy',
  'producttool': 'Product/Tool',
  'social-good': 'Social Good',
  'speculative-design': 'Speculative Design',
  'storytelling': 'Storytelling',
  'uxui': '	UX/UI',
  'vr': 'VR',
  'wearables': 'Wearables',
}
