export const categories = {
  'artdrawing': 'ART/DRAWING',
  'assistive-techhealth': 'ASSISTIVE TECH/HEALTH',
  'data-vizimage-processing': 'DATA VIZ/IMAGE PROCESSING',
  'education': 'EDUCATION',
  'hardware-product-design': 'HARDWARE/PRODUCT DESIGN',
  'immersive-environments': 'IMMERSIVE ENVIRONMENTS',
  'installation': 'INSTALLATION',
  'mobilesocial-media': 'MOBILE/SOCIAL MEDIA',
  'musicsound': 'MUSIC/SOUND',
  'performance': 'PERFORMANCE',
  'social-goodjusticepolitics': 'SOCIAL GOOD/JUSTICE POLITICS',
  'software-design': 'SOFTWARE DESIGN',
  'speculative-design': 'SPECULATIVE DESIGN',
  'storytelling': 'STORYTELLING',
  'timelight': 'TIME/LIGHT',
  'uiux': 'UI/UX',
  'wearables': 'WEARABLES',
}
